export type GalleryImage = {
  id: string;
  src: string;
  alt: string;
  title?: string;
  category?: string;
  width: number;
  height: number;
  featured?: boolean;
};

const images: GalleryImage[] = [
  {
    id: "aust9079",
    src: "/imageGallery/AUST9079.jpg",
    alt: "Warehouse and logistics operations at Dhaka Logistic",
    title: "Warehouse Operations",
    category: "Operations",
    width: 6720,
    height: 4480,
    featured: true,
  },
  {
    id: "aust9158",
    src: "/imageGallery/AUST9158.jpg",
    alt: "Logistics facility and equipment management",
    title: "Facility Management",
    category: "Operations",
    width: 6720,
    height: 4480,
    featured: true,
  },
  {
    id: "img2411",
    src: "/imageGallery/IMG_2411.JPG",
    alt: "Corporate event gathering at DLSS",
    title: "Corporate Event",
    category: "Events",
    width: 6240,
    height: 4160,
    featured: true,
  },
  {
    id: "img2573",
    src: "/imageGallery/IMG_2573.JPG",
    alt: "Professional event ceremony",
    title: "Event Ceremony",
    category: "Events",
    width: 6240,
    height: 4160,
    featured: true,
  },
  {
    id: "img2578",
    src: "/imageGallery/IMG_2578.JPG",
    alt: "Team gathering and celebration event",
    title: "Team Celebration",
    category: "Events",
    width: 6240,
    height: 4160,
    featured: true,
  },
  {
    id: "img2670",
    src: "/imageGallery/IMG_2670.JPG",
    alt: "Conference and seminar event",
    title: "Industry Seminar",
    category: "Events",
    width: 6240,
    height: 4160,
    featured: true,
  },
  {
    id: "img2702",
    src: "/imageGallery/IMG_2702.JPG",
    alt: "Award ceremony and recognition event",
    title: "Award Ceremony",
    category: "Events",
    width: 6240,
    height: 4160,
  },
  {
    id: "img3096",
    src: "/imageGallery/IMG_3096.jpg",
    alt: "Team member portrait outdoors",
    title: "Team Member Portrait",
    category: "Team",
    width: 2000,
    height: 1500,
  },
  {
    id: "img3097",
    src: "/imageGallery/IMG_3097.jpg",
    alt: "Colleague group photo at work",
    title: "Team Group Photo",
    category: "Team",
    width: 2000,
    height: 1500,
  },
  {
    id: "img3113",
    src: "/imageGallery/IMG_3113.jpg",
    alt: "Staff collaboration and teamwork",
    title: "Team Collaboration",
    category: "Team",
    width: 2000,
    height: 1500,
  },
  {
    id: "img1537_6",
    src: "/imageGallery/IMG_1537%20(6).jpg",
    alt: "Team building activity session",
    title: "Team Building",
    category: "Team",
    width: 960,
    height: 720,
  },
  {
    id: "img1537_9",
    src: "/imageGallery/IMG_1537%20(9).jpg",
    alt: "Staff portrait during team event",
    title: "Staff Portrait",
    category: "Team",
    width: 720,
    height: 960,
  },
  {
    id: "img1537_13",
    src: "/imageGallery/IMG_1537%20(13).jpg",
    alt: "Group photo at team outing",
    title: "Team Outing",
    category: "Team",
    width: 960,
    height: 720,
  },
  {
    id: "20190202",
    src: "/imageGallery/20190202_134522.jpg",
    alt: "Site visit and field operation",
    title: "Site Visit",
    category: "Operations",
    width: 4128,
    height: 2322,
  },
  {
    id: "20190720_1",
    src: "/imageGallery/20190720_112936.jpg",
    alt: "On-site service delivery in action",
    title: "Service Delivery",
    category: "Operations",
    width: 4128,
    height: 3096,
  },
  {
    id: "20190720_2",
    src: "/imageGallery/20190720_113028.jpg",
    alt: "Field operations and logistics coordination",
    title: "Field Operations",
    category: "Operations",
    width: 4128,
    height: 3096,
  },
  {
    id: "20210123",
    src: "/imageGallery/20210123_150344.jpg",
    alt: "Modern logistics hub overview",
    title: "Logistics Hub",
    category: "Operations",
    width: 1920,
    height: 1080,
  },
  {
    id: "img4878",
    src: "/imageGallery/IMG_4878.JPG",
    alt: "Office interior and workspace",
    title: "Office Workspace",
    category: "Team",
    width: 2016,
    height: 1512,
  },
  {
    id: "img4895",
    src: "/imageGallery/IMG_4895.JPG",
    alt: "Meeting room discussion",
    title: "Team Meeting",
    category: "Team",
    width: 2016,
    height: 1512,
  },
  {
    id: "img4915",
    src: "/imageGallery/IMG_4915.JPG",
    alt: "Documentation and administrative work",
    title: "Administrative Work",
    category: "Team",
    width: 640,
    height: 480,
  },
  {
    id: "img5720",
    src: "/imageGallery/IMG_5720.jpg",
    alt: "Operational briefing session",
    title: "Operations Briefing",
    category: "Operations",
    width: 2000,
    height: 1500,
  },
  {
    id: "ahd4",
    src: "/imageGallery/AHD_4.jpg",
    alt: "Logistics vehicle and transport management",
    title: "Transport Management",
    category: "Operations",
    width: 2000,
    height: 1125,
  },
  {
    id: "tr1",
    src: "/imageGallery/TR_1.jpg",
    alt: "Transport and logistics fleet",
    title: "Logistics Fleet",
    category: "Operations",
    width: 2000,
    height: 1125,
  },
];

export const galleryImages = images.sort((a, b) => a.id.localeCompare(b.id));
export const featuredImages = images.filter((img) => img.featured);

export const categories = [
  "All",
  ...Array.from(new Set(images.map((img) => img.category!).filter(Boolean))),
];
